spring.application.name: booking-service
server.port: 8081
feign.hystrix.enabled: true
hystrix.command.default.execution.timeout.enabled: false
spring.cloud.stream.bindings.cargoBookingChannel.destination: cargoBookings
spring.cloud.stream.bindings.cargoBookingChannel.binder: rabbit
spring.cloud.stream.bindings.cargoRoutingChannel.destination: cargoRoutings
spring.cloud.stream.bindings.cargoRoutingChannel.binder: rabbit
spring.cloud.stream.bindings.cargoHandlingChannel.destination: cargoHandling
spring.cloud.stream.bindings.cargoHandlingChannel.group: cargoHandlingInBookingQueue
spring.cloud.stream.bindings.cargoHandlingChannel.binder: rabbit
spring.cloud.stream.binders.rabbit.type: rabbit

spring.cloud.stream.binders.rabbit.environment.spring.rabbitmq.host: 172.18.0.4
spring.cloud.stream.binders.rabbit.environment.spring.rabbitmq.port: 5672
spring.cloud.stream.binders.rabbit.environment.spring.rabbitmq.username: guest
spring.cloud.stream.binders.rabbit.environment.spring.rabbitmq.password: guest
spring.jpa.database: MYSQL
spring.jpa.hibernate.ddl-auto: update
spring.datasource.url: jdbc:mysql://172.18.0.3:3306/booking
spring.datasource.password: password
spring.datasource.username: root
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
